//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conductor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public conductor()
        {
            this.itinerario = new HashSet<itinerario>();
        }
    
        public int codigoconductor { get; set; }
        public string nombreconductor { get; set; }
        public string apellidoconductor { get; set; }
        public string dniconductor { get; set; }
        public string direccionconductor { get; set; }
        public string telefonoconductor { get; set; }
        public string correoconductor { get; set; }
        public string estadoconductor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itinerario> itinerario { get; set; }
    }
}
