//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webventapasajeEntities : DbContext
    {
        public webventapasajeEntities()
            : base("name=webventapasajeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asiento> asiento { get; set; }
        public virtual DbSet<bus> bus { get; set; }
        public virtual DbSet<conductor> conductor { get; set; }
        public virtual DbSet<detalleasiento> detalleasiento { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<itinerario> itinerario { get; set; }
        public virtual DbSet<lugar> lugar { get; set; }
        public virtual DbSet<pasaje> pasaje { get; set; }
        public virtual DbSet<pasajero> pasajero { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
    }
}
