//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class itinerario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public itinerario()
        {
            this.pasaje = new HashSet<pasaje>();
        }
    
        public int codigoitinerario { get; set; }
        public Nullable<int> codigolugarorigen { get; set; }
        public Nullable<int> codigolugardestino { get; set; }
        public Nullable<int> codigoservicio { get; set; }
        public Nullable<int> codigobus { get; set; }
        public int codigoconductor { get; set; }
        public Nullable<System.DateTime> fechasalidaitinerario { get; set; }
        public Nullable<System.DateTime> horasalidaitinerario { get; set; }
        public Nullable<System.DateTime> fechallegadaitinerario { get; set; }
        public Nullable<System.DateTime> horallegadaitinerario { get; set; }
        public Nullable<decimal> precioitinerario { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual conductor conductor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pasaje> pasaje { get; set; }
        public virtual lugar lugar { get; set; }
        public virtual lugar lugar1 { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
