//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasajero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pasajero()
        {
            this.pasaje = new HashSet<pasaje>();
        }
    
        public int codigopasajero { get; set; }
        public string nombrepasajero { get; set; }
        public string apellidopasajero { get; set; }
        public string dnipasajero { get; set; }
        public string direccionpasajero { get; set; }
        public string telefonopasajero { get; set; }
        public string correopasajero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pasaje> pasaje { get; set; }
    }
}
