//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasaje
    {
        public int codigopasaje { get; set; }
        public int codigoitinerario { get; set; }
        public int codigopasajero { get; set; }
        public string numeroasientopasaje { get; set; }
        public Nullable<System.DateTime> fechaventapasaje { get; set; }
    
        public virtual itinerario itinerario { get; set; }
        public virtual pasajero pasajero { get; set; }
    }
}
